# Example catalog-info.yaml entity definition file
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    name: gitlab-test2
    annotations:
        #gitlab.com/project-id: '567'
        # gitlab.com/project-id: '572'
        #gitlab.com/project-id: '47834958' #1234. This must be in quotes and can be found under Settings --> General
        #gitlab.com/project-slug: 'backdora-test'
        https://gitlab.logius.plp.cloud/project-slug: 'Backdora Test'
        
spec:
    type: service
    owner: john@example.com
    lifecycle: experimental
